version: "3"

volumes:
  postgres_data: {}

services:
  postgresql:
    image: postgres:15.4-alpine
    ports:
      - ${CHAINSTORAGE_TEMPORAL_POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
    volumes:
      - postgres_data:/var/lib/postgresql/data
  temporal:
    image: temporalio/auto-setup:1.22.0
    depends_on:
      - postgresql
    ports:
      - 7233:7233
    labels:
      service_group: temporal
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - USE_HOSTNAME_IP=true
    restart: always
  temporal-ui:
    image: temporalio/ui:2.18.2
    ports:
      - 8088:8080
    labels:
      service_group: temporal-web
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal
  temporal-admin-tools:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.22.0
    stdin_open: true
    tty: true
