aws:
  aws_account: development
  bucket: chainstorage-ethereum-mainnet-dev
  dlq:
    name: chainstorage_blocks_ethereum_mainnet_dlq
  dynamodb:
    block_table: chainstorage_blocks_ethereum_mainnet
    event_table: chainstorage_block_events_ethereum_mainnet
    event_table_height_index: chainstorage_block_events_by_height_eth_main
chain:
  client:
    master:
      endpoint_group: |
        {
          "endpoints": [
            {
              "name": "eth-rpc-nodes-erigon-prysm-sticky",
              "url": "https://ethereum-mainnet.s.chainbase.online/v1/2c6jWYuGAvg7GqwVaxe8Uj1FBat",
              "weight": 1
            }
          ],
          "sticky_session": {
            "header_hash": "x-session-hash"
          }
        }
    slave:
      endpoint_group: |
        {
          "endpoints": [
            {
              "name": "eth-rpc-nodes-erigon-prysm-round-robin",
              "url": "https://ethereum-mainnet.s.chainbase.online/v1/2c6jWYuGAvg7GqwVaxe8Uj1FBat",
              "weight": 1
            }
          ]
        }
  block_tag:
    latest: 2
    stable: 2
  block_time: 12s
  event_tag:
    latest: 3
    stable: 3
  irreversible_distance: 12
  feature:
    rosetta_parser: true
    default_stable_event: true
    block_validation_enabled: true
    block_validation_muted: true
sla:
  block_height_delta: 10
  block_time_delta: 2m
  out_of_sync_node_distance: 10
  tier: 1
  time_since_last_block: 2m
  event_height_delta: 10
  event_time_delta: 2m
  time_since_last_event: 2m
  expected_workflows:
    - monitor
    - poller
    - streamer
    - cross_validator
workflows:
  backfiller:
    checkpoint_size: 5000
    num_concurrent_extractors: 24
  cross_validator:
    batch_size: 1000
    validation_start_height: 15500000
    validation_percentage: 1
  poller:
    parallelism: 10
    failover_enabled: true
    session_enabled: true
    backoff_interval: 1s
    consensus_validation: true
    consensus_validation_muted: true
  monitor:
    failover_enabled: true
  streamer:
    backoff_interval: 1s
